name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - run: |
        dd if=/dev/urandom of=randomfile bs=1M count=100
        CORRECT="$(md5sum < randomfile)"
        TEST="$(go run ./cmd/fv/ < randomfile | md5sum)"
        if [ "$CORRECT" != "$TEST" ]; then
          echo "Bug!"
          exit 1
        fi
 
